Repository Neurosim-lab/netpyne, pull requests merged in 2018-09, with the labels that each got.

#355 add exp, log, etc to validate func
  netpyne/utils.py
Labels: ready

#357 avoid time_stamps concatenation
  netpyne/simFuncs.py
Labels: ready

#365 Py3 pickle compatibility
  netpyne/simFuncs.py
  netpyne/specs.py
Labels: in progress

#359 Fastspkt
  df.pkl
  netpyne/analysis.py
Labels: in progress

#352 create script from .json or netParams, simConfig Objects
  netpyne/utils.py
Labels: enhancement, in progress

#376 Travis py3
  .travis.yml
  doc/source/code/netcon.inc
  examples/HybridTut/izhi2007b.mod
  examples/LFPrecording/PT5B_full_cellParams.json
  examples/M1/izhi2007b.mod
  netpyne/sim/load.py
  netpyne/specs/netParams.py
Labels: in progress
